/* Generated by CIL v. 8a05afd */
/* print_CIL_Input is false */

#line 31 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __u_char;
#line 32 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __u_short;
#line 33 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __u_int;
#line 34 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_long;
#line 37 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef signed char __int8_t;
#line 38 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __uint8_t;
#line 39 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef short __int16_t;
#line 40 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __uint16_t;
#line 41 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __int32_t;
#line 42 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uint32_t;
#line 44 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __int64_t;
#line 45 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uint64_t;
#line 52 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int8_t __int_least8_t;
#line 53 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint8_t __uint_least8_t;
#line 54 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int16_t __int_least16_t;
#line 55 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint16_t __uint_least16_t;
#line 56 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int32_t __int_least32_t;
#line 57 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint32_t __uint_least32_t;
#line 58 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int64_t __int_least64_t;
#line 59 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint64_t __uint_least64_t;
#line 63 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __quad_t;
#line 64 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_quad_t;
#line 72 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intmax_t;
#line 73 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uintmax_t;
#line 145 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
#line 146 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
#line 147 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
#line 148 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
#line 149 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino64_t;
#line 150 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 151 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
#line 152 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 154 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __pid_t;
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
struct __anonstruct_0 {
   int __val[2] ;
};
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef struct __anonstruct_0 __fsid_t;
#line 156 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __clock_t;
#line 157 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim_t;
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim64_t;
#line 159 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __id_t;
#line 160 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 161 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __useconds_t;
#line 162 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds_t;
#line 163 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds64_t;
#line 165 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __daddr_t;
#line 166 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __key_t;
#line 169 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __clockid_t;
#line 172 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef void *__timer_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
#line 180 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
#line 181 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt64_t;
#line 184 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt_t;
#line 185 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt64_t;
#line 188 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt_t;
#line 189 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt64_t;
#line 192 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __fsword_t;
#line 194 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __ssize_t;
#line 197 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 199 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __syscall_ulong_t;
#line 203 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __off64_t __loff_t;
#line 204 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef char *__caddr_t;
#line 207 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intptr_t;
#line 210 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __socklen_t;
#line 215 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __sig_atomic_t;
#line 24 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h"
typedef __int8_t int8_t;
#line 25 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h"
typedef __int16_t int16_t;
#line 26 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h"
typedef __int32_t int32_t;
#line 27 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h"
typedef __int64_t int64_t;
#line 24 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h"
typedef __uint8_t uint8_t;
#line 25 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h"
typedef __uint16_t uint16_t;
#line 26 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h"
typedef __uint32_t uint32_t;
#line 27 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h"
typedef __uint64_t uint64_t;
#line 43 "/usr/include/stdint.h"
typedef __int_least8_t int_least8_t;
#line 44 "/usr/include/stdint.h"
typedef __int_least16_t int_least16_t;
#line 45 "/usr/include/stdint.h"
typedef __int_least32_t int_least32_t;
#line 46 "/usr/include/stdint.h"
typedef __int_least64_t int_least64_t;
#line 49 "/usr/include/stdint.h"
typedef __uint_least8_t uint_least8_t;
#line 50 "/usr/include/stdint.h"
typedef __uint_least16_t uint_least16_t;
#line 51 "/usr/include/stdint.h"
typedef __uint_least32_t uint_least32_t;
#line 52 "/usr/include/stdint.h"
typedef __uint_least64_t uint_least64_t;
#line 58 "/usr/include/stdint.h"
typedef signed char int_fast8_t;
#line 60 "/usr/include/stdint.h"
typedef long int_fast16_t;
#line 61 "/usr/include/stdint.h"
typedef long int_fast32_t;
#line 62 "/usr/include/stdint.h"
typedef long int_fast64_t;
#line 71 "/usr/include/stdint.h"
typedef unsigned char uint_fast8_t;
#line 73 "/usr/include/stdint.h"
typedef unsigned long uint_fast16_t;
#line 74 "/usr/include/stdint.h"
typedef unsigned long uint_fast32_t;
#line 75 "/usr/include/stdint.h"
typedef unsigned long uint_fast64_t;
#line 87 "/usr/include/stdint.h"
typedef long intptr_t;
#line 90 "/usr/include/stdint.h"
typedef unsigned long uintptr_t;
#line 101 "/usr/include/stdint.h"
typedef __intmax_t intmax_t;
#line 102 "/usr/include/stdint.h"
typedef __uintmax_t uintmax_t;
#line 46 "/usr/include/clang/13.0.1/include/stddef.h"
typedef unsigned long size_t;
#line 14 "/usr/include/clang/13.0.1/include/stdarg.h"
typedef __builtin_va_list va_list;
#line 32 "/usr/include/clang/13.0.1/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
#line 16 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
union __anonunion_2 {
   unsigned int __wch ;
   char __wchb[4] ;
};
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
struct __anonstruct_1 {
   int __count ;
   union __anonunion_2 __value ;
};
#line 21 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
typedef struct __anonstruct_1 __mbstate_t;
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
struct _G_fpos_t {
   __off_t __pos ;
   __mbstate_t __state ;
};
#line 14 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
typedef struct _G_fpos_t __fpos_t;
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
struct _G_fpos64_t {
   __off64_t __pos ;
   __mbstate_t __state ;
};
#line 14 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
typedef struct _G_fpos64_t __fpos64_t;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE ;
#line 5 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
typedef struct _IO_FILE __FILE;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
struct _IO_FILE ;
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
#line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE ;
#line 36
struct _IO_marker ;
#line 37
struct _IO_codecvt ;
#line 38
struct _IO_wide_data ;
#line 43 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
#line 49 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[20] ;
};
#line 52 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
#line 63 "/usr/include/stdio.h"
typedef __off_t off_t;
#line 77 "/usr/include/stdio.h"
typedef __ssize_t ssize_t;
#line 84 "/usr/include/stdio.h"
typedef __fpos_t fpos_t;
#line 214 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h"
typedef float _Float32;
#line 251 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h"
typedef double _Float64;
#line 268 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h"
typedef double _Float32x;
#line 285 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h"
typedef long double _Float64x;
#line 11 "../original/patch/jasper.c"
struct jpc_siz {
   unsigned int width ;
   unsigned int height ;
   unsigned int tilewidth ;
   unsigned int tileheight ;
   unsigned int tilexoff ;
   unsigned int tileyoff ;
   unsigned int xoff ;
};
#line 19 "../original/patch/jasper.c"
typedef struct jpc_siz jpc_siz_t;
#line 21 "../original/patch/jasper.c"
struct jpc_params {
   jpc_siz_t siz ;
};
#line 23 "../original/patch/jasper.c"
typedef struct jpc_params jpc_params_t;
#line 25 "../original/patch/jasper.c"
struct jpc_ms {
   jpc_params_t parms ;
};
#line 27 "../original/patch/jasper.c"
typedef struct jpc_ms jpc_ms_t;
#line 29 "../original/patch/jasper.c"
struct jpc_cstate {
   int dummy ;
};
#line 31 "../original/patch/jasper.c"
typedef struct jpc_cstate jpc_cstate_t;
#line 33 "../original/patch/jasper.c"
struct jpc_dec_tile {
   unsigned int xstart ;
};
#line 35 "../original/patch/jasper.c"
typedef struct jpc_dec_tile jpc_dec_tile_t;
#line 37 "../original/patch/jasper.c"
struct jpc_dec {
   unsigned int xend ;
   unsigned int yend ;
   unsigned int tilewidth ;
   unsigned int tileheight ;
   unsigned int tilexoff ;
   unsigned int tileyoff ;
   unsigned int numhtiles ;
   unsigned int numvtiles ;
   unsigned int numtiles ;
   unsigned int xstart ;
   jpc_dec_tile_t *tiles ;
};
#line 49 "../original/patch/jasper.c"
typedef struct jpc_dec jpc_dec_t;
#line 51 "../original/patch/jasper.c"
struct jas_stream {
   int *dummy ;
};
#line 53 "../original/patch/jasper.c"
typedef struct jas_stream jas_stream_t;
#line 143 "/usr/include/stdio.h"
extern FILE *stdin ;
#line 144
extern FILE *stdout ;
#line 145
extern FILE *stderr ;
#line 152
extern  __attribute__((__nothrow__)) int remove(char const   *__filename ) ;
#line 154
extern  __attribute__((__nothrow__)) int rename(char const   *__old , char const   *__new ) ;
#line 158
extern  __attribute__((__nothrow__)) int renameat(int __oldfd , char const   *__old ,
                                                  int __newfd , char const   *__new ) ;
#line 178
extern int fclose(FILE *__stream ) ;
#line 188
extern FILE *tmpfile(void) ;
#line 205
extern  __attribute__((__nothrow__)) char *tmpnam(char [20] ) ;
#line 210
extern  __attribute__((__nothrow__)) char *tmpnam_r(char __s[20] ) ;
#line 222
extern  __attribute__((__nothrow__)) char *tempnam(char const   *__dir , char const   *__pfx ) ;
#line 230
extern int fflush(FILE *__stream ) ;
#line 239
extern int fflush_unlocked(FILE *__stream ) ;
#line 258
extern FILE *fopen(char const   *__filename , char const   *__modes ) ;
#line 265
extern FILE *freopen(char const   *__filename , char const   *__modes , FILE *__stream ) ;
#line 293
extern  __attribute__((__nothrow__)) FILE *fdopen(int __fd , char const   *__modes ) ;
#line 308
extern  __attribute__((__nothrow__)) FILE *fmemopen(void *__s , size_t __len , char const   *__modes ) ;
#line 314
extern  __attribute__((__nothrow__)) FILE *open_memstream(char **__bufloc , size_t *__sizeloc ) ;
#line 328
extern  __attribute__((__nothrow__)) void setbuf(FILE *__stream , char *__buf ) ;
#line 332
extern  __attribute__((__nothrow__)) int setvbuf(FILE *__stream , char *__buf , int __modes ,
                                                 size_t __n ) ;
#line 338
extern  __attribute__((__nothrow__)) void setbuffer(FILE *__stream , char *__buf ,
                                                    size_t __size ) ;
#line 342
extern  __attribute__((__nothrow__)) void setlinebuf(FILE *__stream ) ;
#line 350
extern int fprintf(FILE *__stream , char const   *__format  , ...) ;
#line 356
extern int printf(char const   *__format  , ...) ;
#line 358
extern  __attribute__((__nothrow__)) int sprintf(char *__s , char const   *__format 
                                                 , ...) ;
#line 365
extern int vfprintf(FILE *__s , char const   *__format , __gnuc_va_list __arg ) ;
#line 371
extern int vprintf(char const   *__format , __gnuc_va_list __arg ) ;
#line 373
extern  __attribute__((__nothrow__)) int vsprintf(char *__s , char const   *__format ,
                                                  __gnuc_va_list __arg ) ;
#line 378
extern  __attribute__((__nothrow__)) int snprintf(char *__s , size_t __maxlen , char const   *__format 
                                                  , ...) ;
#line 382
extern  __attribute__((__nothrow__)) int vsnprintf(char *__s , size_t __maxlen , char const   *__format ,
                                                   __gnuc_va_list __arg ) ;
#line 403
extern int vdprintf(int __fd , char const   *__fmt , __gnuc_va_list __arg ) ;
#line 406
extern int dprintf(int __fd , char const   *__fmt  , ...) ;
#line 415
extern int fscanf(FILE *__stream , char const   *__format  , ...) ;
#line 421
extern int scanf(char const   *__format  , ...) ;
#line 423
extern  __attribute__((__nothrow__)) int sscanf(char const   *__s , char const   *__format 
                                                , ...) ;
#line 434
extern int fscanf(FILE *__stream , char const   *__format  , ...) ;
#line 437
extern int scanf(char const   *__format  , ...) ;
#line 439
extern  __attribute__((__nothrow__)) int sscanf(char const   *__s , char const   *__format 
                                                , ...) ;
#line 459
extern int vfscanf(FILE *__s , char const   *__format , __gnuc_va_list __arg ) ;
#line 467
extern int vscanf(char const   *__format , __gnuc_va_list __arg ) ;
#line 471
extern  __attribute__((__nothrow__)) int vsscanf(char const   *__s , char const   *__format ,
                                                 __gnuc_va_list __arg ) ;
#line 479
extern int vfscanf(FILE *__s , char const   *__format , __gnuc_va_list __arg ) ;
#line 484
extern int vscanf(char const   *__format , __gnuc_va_list __arg ) ;
#line 487
extern  __attribute__((__nothrow__)) int vsscanf(char const   *__s , char const   *__format ,
                                                 __gnuc_va_list __arg ) ;
#line 513
extern int fgetc(FILE *__stream ) ;
#line 514
extern int getc(FILE *__stream ) ;
#line 520
extern int getchar(void) ;
#line 527
extern int getc_unlocked(FILE *__stream ) ;
#line 528
extern int getchar_unlocked(void) ;
#line 538
extern int fgetc_unlocked(FILE *__stream ) ;
#line 549
extern int fputc(int __c , FILE *__stream ) ;
#line 550
extern int putc(int __c , FILE *__stream ) ;
#line 556
extern int putchar(int __c ) ;
#line 565
extern int fputc_unlocked(int __c , FILE *__stream ) ;
#line 573
extern int putc_unlocked(int __c , FILE *__stream ) ;
#line 574
extern int putchar_unlocked(int __c ) ;
#line 581
extern int getw(FILE *__stream ) ;
#line 584
extern int putw(int __w , FILE *__stream ) ;
#line 592
extern char *fgets(char *__s , int __n , FILE *__stream ) ;
#line 632
extern __ssize_t __getdelim(char **__lineptr , size_t *__n , int __delimiter , FILE *__stream ) ;
#line 635
extern __ssize_t getdelim(char **__lineptr , size_t *__n , int __delimiter , FILE *__stream ) ;
#line 645
extern __ssize_t getline(char **__lineptr , size_t *__n , FILE *__stream ) ;
#line 655
extern int fputs(char const   *__s , FILE *__stream ) ;
#line 661
extern int puts(char const   *__s ) ;
#line 668
extern int ungetc(int __c , FILE *__stream ) ;
#line 675
extern unsigned long fread(void *__ptr , size_t __size , size_t __n , FILE *__stream ) ;
#line 681
extern unsigned long fwrite(void const   *__ptr , size_t __size , size_t __n , FILE *__s ) ;
#line 702
extern size_t fread_unlocked(void *__ptr , size_t __size , size_t __n , FILE *__stream ) ;
#line 704
extern size_t fwrite_unlocked(void const   *__ptr , size_t __size , size_t __n , FILE *__stream ) ;
#line 713
extern int fseek(FILE *__stream , long __off , int __whence ) ;
#line 718
extern long ftell(FILE *__stream ) ;
#line 723
extern void rewind(FILE *__stream ) ;
#line 736
extern int fseeko(FILE *__stream , __off_t __off , int __whence ) ;
#line 741
extern __off_t ftello(FILE *__stream ) ;
#line 760
extern int fgetpos(FILE *__stream , fpos_t *__pos ) ;
#line 765
extern int fsetpos(FILE *__stream , fpos_t *__pos ) ;
#line 786
extern  __attribute__((__nothrow__)) void clearerr(FILE *__stream ) ;
#line 788
extern  __attribute__((__nothrow__)) int feof(FILE *__stream ) ;
#line 790
extern  __attribute__((__nothrow__)) int ferror(FILE *__stream ) ;
#line 794
extern  __attribute__((__nothrow__)) void clearerr_unlocked(FILE *__stream ) ;
#line 795
extern  __attribute__((__nothrow__)) int feof_unlocked(FILE *__stream ) ;
#line 796
extern  __attribute__((__nothrow__)) int ferror_unlocked(FILE *__stream ) ;
#line 804
extern void perror(char const   *__s ) ;
#line 809
extern  __attribute__((__nothrow__)) int fileno(FILE *__stream ) ;
#line 814
extern  __attribute__((__nothrow__)) int fileno_unlocked(FILE *__stream ) ;
#line 823
extern int pclose(FILE *__stream ) ;
#line 829
extern FILE *popen(char const   *__command , char const   *__modes ) ;
#line 837
extern  __attribute__((__nothrow__)) char *ctermid(char *__s ) ;
#line 867
extern  __attribute__((__nothrow__)) void flockfile(FILE *__stream ) ;
#line 871
extern  __attribute__((__nothrow__)) int ftrylockfile(FILE *__stream ) ;
#line 874
extern  __attribute__((__nothrow__)) void funlockfile(FILE *__stream ) ;
#line 885
extern int __uflow(FILE * ) ;
#line 886
extern int __overflow(FILE * , int  ) ;
#line 57 "../original/patch/jasper.c"
void init_source(jpc_ms_t *ms , jas_stream_t *in ) 
{ 
  int *fp ;
  FILE *__cil_tmp4 ;
  int __cil_tmp5 ;

  {
  {
#line 58
  __cil_tmp4 = fopen((char const   *)"dummy.c", (char const   *)"rb");
#line 58
  fp = __cil_tmp4;
#line 59
  ms->parms.siz.width = (unsigned int )0;
#line 60
  ms->parms.siz.height = (unsigned int )0;
#line 61
  ms->parms.siz.tilewidth = (unsigned int )0;
#line 62
  ms->parms.siz.tileheight = (unsigned int )0;
#line 63
  ms->parms.siz.tilexoff = (unsigned int )0;
#line 64
  ms->parms.siz.tileyoff = (unsigned int )0;
#line 65
  in->dummy = (int *)malloc((unsigned long )1028);
#line 66
  fread(in->dummy, (unsigned long )1028, (unsigned long )1, fp);
#line 67
  fclose(fp);
  }
  return;
}
}
#line 70 "../original/patch/jasper.c"
int jas_stream_getc(jas_stream_t *in ) 
{ 
  int *__cil_tmp2 ;

  {
#line 71
  __cil_tmp2 = in->dummy;
#line 71
  (in->dummy) ++;
#line 71
  return (*__cil_tmp2);
}
}
#line 74 "../original/patch/jasper.c"
int jpc_getuint32(jas_stream_t *in , unsigned int *val ) 
{ 
  unsigned int v ;
  int c ;
  int __cil_tmp5 ;
  int __cil_tmp6 ;
  int __cil_tmp7 ;
  int __cil_tmp8 ;

  {
  {
#line 78
  c = jas_stream_getc(in);
  }
#line 78
  if (c == -1) {
#line 79
    return (- 1);
  }
  {
#line 81
  v = (unsigned int )c;
#line 82
  c = jas_stream_getc(in);
  }
#line 82
  if (c == -1) {
#line 83
    return (- 1);
  }
  {
#line 85
  v = (v << 8) | (unsigned int )c;
#line 86
  c = jas_stream_getc(in);
  }
#line 86
  if (c == -1) {
#line 87
    return (- 1);
  }
  {
#line 89
  v = (v << 8) | (unsigned int )c;
#line 90
  c = jas_stream_getc(in);
  }
#line 90
  if (c == -1) {
#line 91
    return (- 1);
  }
#line 93
  v = (v << 8) | (unsigned int )c;
#line 94
  if (val) {
#line 95
    *val = v;
  }
#line 97
  return (0);
}
}
#line 100 "../original/patch/jasper.c"
int jpc_siz_getparms(jpc_ms_t *ms , jpc_cstate_t *cstate , jas_stream_t *in ) 
{ 
  jpc_siz_t *siz ;

  {
  {
#line 102
  siz = & ms->parms.siz;
#line 104
  jpc_getuint32(in, & siz->width);
#line 105
  jpc_getuint32(in, & siz->height);
#line 106
  jpc_getuint32(in, & siz->tilewidth);
#line 107
  jpc_getuint32(in, & siz->tileheight);
#line 108
  jpc_getuint32(in, & siz->tilexoff);
#line 109
  jpc_getuint32(in, & siz->tileyoff);
#line 110
  jpc_getuint32(in, & siz->xoff);
  }
#line 112
  if (siz->tilexoff > siz->xoff) {
    {
    {
#line 113
    jas_eprintf("XTOsiz not in permissible range\n\300\306\340\231\243U");
    }
    }
#line 114
    return (- 1);
  } else
#line 112
  if (siz->tilexoff + siz->tilewidth <= siz->xoff) {
    {
    {
#line 113
    jas_eprintf("XTOsiz not in permissible range\n\300\306\340\231\243U");
    }
    }
#line 114
    return (- 1);
  }
#line 117
  return (0);
}
}
#line 120 "../original/patch/jasper.c"
int jpc_dec_process_siz(jpc_dec_t *dec , jpc_ms_t *ms ) 
{ 
  jpc_siz_t *siz ;
  jpc_dec_tile_t *tile ;
  int __cil_tmp5 ;
  int tileno ;
  int htileno ;
  unsigned int start ;
  unsigned int tmp ;

  {
  {
#line 122
  siz = & ms->parms.siz;
#line 125
  dec->xstart = siz->xoff;
#line 126
  dec->xend = siz->width;
#line 127
  dec->yend = siz->height;
#line 128
  dec->tilewidth = siz->tilewidth;
#line 129
  dec->tileheight = siz->tileheight;
#line 130
  dec->tilexoff = siz->tilexoff;
#line 131
  dec->tileyoff = siz->tileyoff;
#line 134
  dec->numhtiles = (((dec->xend - dec->tilexoff) + dec->tilewidth) - 1U) / dec->tilewidth;
#line 135
  dec->numvtiles = (((dec->yend - dec->tileyoff) + dec->tileheight) - 1U) / dec->tileheight;
#line 136
  dec->numtiles = dec->numhtiles * dec->numvtiles;
#line 137
  dec->tiles = (jpc_dec_tile_t *)calloc((unsigned long )dec->numtiles, sizeof(jpc_dec_tile_t ));
#line 139
  tileno = 0;
  }
  {
#line 139
  while (1) {
    while_continue: /* CIL Label */ ;
#line 139
    if (! ((unsigned int )tileno < dec->numtiles)) {
#line 139
      goto while_break;
    }
#line 141
    htileno = (int )((unsigned int )tileno % dec->numhtiles);
#line 142
    if (dec->tilexoff + (unsigned int )htileno * dec->tilewidth > dec->xstart) {
#line 142
      tmp = dec->tilexoff + (unsigned int )htileno * dec->tilewidth;
    } else {
#line 142
      tmp = dec->xstart;
    }
#line 142
    start = tmp;
#line 139
    tileno ++;
  }
  while_break: /* CIL Label */ ;
  }
#line 146
  return (0);
}
}
#line 149 "../original/patch/jasper.c"
int main(int argc , char **argv ) 
{ 
  jpc_ms_t ms ;
  jpc_cstate_t cstate ;
  jas_stream_t in ;
  jpc_dec_t dec ;

  {
  {
#line 154
  init_source(& ms, & in);
#line 155
  jpc_siz_getparms(& ms, & cstate, & in);
#line 156
  jpc_dec_process_siz(& dec, & ms);
  }
#line 157
  return (0);
}
}
