language: c

dist: trusty
sudo: false
#group: beta

os:
    - linux
    - osx

#osx_image:
#    - xcode7.3
#    #- xcode8

compiler:
    - clang
    - gcc

before_install:
    - bash --version
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated bash || brew upgrade bash; fi
#    - bash --version

install: autoreconf -i

script:
    - ./configure --prefix=/tmp/jasper && make clean && make && make install
    - make check || (cat test/bin/run_test_*.log; exit 1)

notifications:
    email:
        on_success: change
        on_failure: always

